apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-pwfile
spec:
  secretStoreRef:
    name: house-vault
    kind: ClusterSecretStore
  target:
    name: mosquitto-pwfile
  dataFrom:
    - extract:
        key: house/mosquitto/pwfile
