apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  template:
    spec:
      containers:
        - name: mosquitto
          image: docker.io/eclipse-mosquitto
          args:
            - mosquitto
            - -c
            - /config/mosquitto.conf
          ports:
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /config
            - name: mosquitto-pwfile
              mountPath: /pwfile
            - name: mosquitto-data
              mountPath: /data
      securityContext:
        runAsGroup: 1883
        runAsUser: 1883
        fsGroup: 1883
        runAsNonRoot: true
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-pwfile
          secret:
            secretName: mosquitto-pwfile
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
