apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto
commonLabels:
  app: mosquitto

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: mosquitto-config
    files:
      - config/mosquitto.conf
