apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

secretGenerator:
  - name: mosquitto-pwfile
    files:
      - secrets/pwfile

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: mosquitto
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.215
