apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.215
  ports:
    - port: 1883
      name: mqtt
      protocol: TCP
      targetPort: mqtt
